### PR TITLE
Update Swift 4.2

### PR DESCRIPTION
**Pull request by balitax**

### CODE REVIEW

**Comment by dielsonsales** [comment]
Is this library abandoned? I've tested this update and everything is working fine.

**Comment by balitax** [comment]
last I've try this library in Xcode 10, using swift 4.2 not work @dielsonsales

**Comment by dielsonsales** [comment]
@balitax I mean after your PR. It is a straightforward update but wasn't merged yet.

**Comment by aleincerto** [comment]
Please approve this PR!

**Review by gmunhoz — APPROVED** [review]

**Pull request merged**
